/* Generates gym/docs/EXAMPLE-REPORTS.md from the real engines using SIMULATED
   users. Everything it writes is demonstration data. Run: node gym/test/example-reports.js */
const fs = require('fs'), path = require('path');
const K = require('./simkit.js');
const { P, R, MON, add, msOf, newUser, weekAt, perform, runWeek, reviewOf, GOOD, HARD, X } = K;
const out = [];
const w = (s) => out.push(s);
const name = id => (X.EX_INDEX[id] || {}).short || id;

w('# Example weekly reports (demonstration data)\n');
w('> **Demonstration data.** Every user, session, set and note below was generated by a script (`gym/test/example-reports.js`) to show what the planning engine and weekly review produce. None of it is a real person\'s training. The reports are produced by the same code the app runs, and the "saved plan change" lines are read back from the plan after it was changed.\n');
w('No AI service was called. The written feedback section in the app comes from the configured AI service when there is one; otherwise the statistics summary shown here is used and is labelled as not written by AI.\n');

function section(title, s, week, r, accept, nowDate) {
  w(`## ${title}\n`);
  const st = r.stats;
  w(`Week ${week.start} to ${week.end}. Planned ${st.planned}, completed ${st.completed}, partial ${st.partial}, not done ${st.missed + st.skipped}, extra workouts ${st.additional}, training days ${st.uniqueTrainingDays}, planned completion ${st.completionPct}%.\n`);
  const list = (h, a) => { if (a.length) { w(`**${h}**\n`); a.forEach(x => w(`- ${x}`)); w(''); } };
  list('Recorded', r.facts.map(f => f.text)); list('Needs attention', r.attention.map(f => f.text));
  list('Reported by the user', r.reported.map(f => f.text)); list('Tentative readings', r.interpretations.map(f => f.text + ' (tentative)'));
  list('Where the records disagree', r.contradictions); list('Gaps in the data', r.dataGaps);
  if (r.notesConsidered.length) list('Written updates considered', r.notesConsidered.map(n => `${n.date} [${n.category || 'update'}]${n.selfReported ? ' (self-reported)' : ''}: ${n.text}`));
  const live = r.proposals.filter(p => !p.informational);
  if (live.length) { w('**Proposals**\n'); live.forEach(p => { w(`- **${p.title}**${p.needsConfirm ? ' (needs confirmation)' : ''}: ${p.reason}`); p.ops.forEach(o => w(`  - op \`${o.op}\`: ${o.text}`)); }); w(''); }
  else w('**Proposals:** none. The plan stays as it is.\n');
  if (accept) {
    const before = s.plan.versions.length;
    const sel = live.filter(p => !p.needsConfirm).map(p => p.id);
    const res = R.finaliseReport(s, r, 'accept', sel, msOf(nowDate), nowDate);
    w(`**Saved plan change after accepting** (plan versions ${before} to ${s.plan.versions.length}):\n`);
    if (res.applied.length) res.applied.forEach(a => w(`- ${a}`)); else w('- Nothing changed.');
    w('');
  }
}

// 1 consistent progress
{ const s = newUser(); let wk; for (let i = 0; i < 3; i++) wk = runWeek(s, add(MON, i * 7), () => ({ feedback: GOOD }));
  section('Scenario 1: consistent progress', s, wk, reviewOf(s, wk, { overall: 4, energy: 4, sleep: 4, soreness: 2 }), true, wk.end); }
// 2 reps up, weight same
{ const s = newUser(); runWeek(s, MON, () => ({ feedback: GOOD })); const wk = runWeek(s, add(MON, 7), () => ({ feedback: GOOD }));
  section('Scenario 2: reps improve at the same weight', s, wk, reviewOf(s, wk, { overall: 4, energy: 4 }), true, wk.end); }
// 3 low energy + underperformance
{ const s = newUser(); runWeek(s, MON, () => ({ feedback: GOOD }));
  const wk = runWeek(s, add(MON, 7), () => ({ feedback: HARD, reps: (e, set) => Math.max(1, set.plannedReps - 3) }));
  section('Scenario 3: low energy and repeated underperformance', s, wk, reviewOf(s, wk, { overall: 2, energy: 1, sleep: 2, soreness: 4 }), true, wk.end); }
// 4 busy week
{ const s = newUser(); const wk = runWeek(s, MON, (i) => i === 3 ? 'skip' : { feedback: GOOD });
  const sk = wk.slots.find(x => x.status === 'missed'); P.skipSlot(s, sk.id, 'Work ran over', 'time');
  section('Scenario 4: a busy week', s, wk, reviewOf(s, wk, { overall: 3, energy: 3, fit: 'too_long', next: { minutes: 35 } }), true, wk.end); }
// 5 extra workout
{ const s = newUser(); const wk = weekAt(s, MON); const tr = wk.slots.filter(x => x.kind === 'training');
  perform(s, tr[0].id, tr[0].date, { feedback: GOOD });
  const lib = require('../public/library.js'); const wo = lib.searchWorkouts({ kind: 'hypertrophy' })[0];
  const pv = P.previewExtra(s, wo, add(MON, 1), add(MON, 1));
  w('## Scenario 5: an extra workout is added\n'); w(`Preview before adding "${wo.name}": ${pv.advice} Week without it: ${pv.before.level}; with it: ${pv.after.level}. Proposed adjustments: ${pv.changes.length ? pv.changes.map(c => c.text).join(' ') : 'none needed'}\n`);
  const applied = P.applyChanges(s, pv.changes, { source: 'extra', todayISO: add(MON, 1) });
  const sess = require('../public/core.js').newSession(1, add(MON, 1)); sess.extra = true; sess.status = 'completed'; sess.startedAt = msOf(add(MON, 1), 7); sess.endedAt = msOf(add(MON, 1), 8);
  wo.blocks.filter(b => b.type === 'resistance').forEach(b => b.exercises.forEach(e => { const en = require('../public/core.js').newEntry(e.id, e.id); for (let i = 0; i < e.sets; i++) { const st = require('../public/core.js').newSet({ weight: 30, reps: 10 }); require('../public/core.js').editSet(st, 30, 10); en.sets.push(st); } sess.entries.push(en); }));
  s.sessions.push(sess); P.registerExtra(s, { date: add(MON, 1), workoutId: wo.id, sessionId: sess.id });
  for (let i = 1; i < 4; i++) perform(s, tr[i].id, tr[i].date, { feedback: GOOD }); P.reconcile(s, add(wk.end, 1));
  w(`Applied to the remaining sessions: ${applied.length ? applied.join(' ') : 'nothing'}\n`);
  section('Scenario 5 report', s, wk, reviewOf(s, wk, null), false, wk.end); }
// 6 missed, rescheduled without cramming
{ const s = newUser(); const wk = weekAt(s, MON); const tr = wk.slots.filter(x => x.kind === 'training'); P.reconcile(s, add(MON, 2));
  const sug = P.suggestReschedule(s, tr[0].id, add(MON, 2));
  w('## Scenario 6: missed sessions are rescheduled without cramming\n');
  w(`On Wednesday, ${tr[0].label} (Monday) and ${tr[1].label} (Tuesday) are marked missed and kept in history. Safe days offered for ${tr[0].label}: ${sug.options.length ? sug.options.map(o => o.date).join(', ') : 'none. ' + sug.note}\n`);
  const bad = P.moveSlot(s, tr[3].id, tr[2].date, 'x', add(MON, 2)); w(`Trying to stack ${tr[3].label} on ${tr[2].label}'s day: refused, "${bad.problems[0]}"\n`);
  w(`Training sessions next week stay at ${P.ensureWeek(s, add(wk.end, 1)).slots.filter(x => x.kind === 'training').length}, so the missed ones are not added on top.\n`); }
// 7 pain
{ const s = newUser(); const wk = runWeek(s, MON, () => ({ feedback: GOOD }));
  section('Scenario 7: pain follows a separate pathway', s, wk, reviewOf(s, wk, { overall: 3, energy: 3, pain: [{ area: 'left knee', note: 'twinge on squats' }], difficulty: { 'bench-barbell': 'easy', 'lat-pulldown': 'easy' } }), true, wk.end); }
// 8 goal / equipment change
{ const s = newUser(); const wk = runWeek(s, MON, () => ({ feedback: GOOD }));
  const res = P.changeGoals(s, { primary: 'strength', daysPerWeek: 3, equipment: { barbell: true, dumbbell: true, machine: false, cable: false, bands: true, kettlebell: false, bodyweight: true } }, add(MON, 6), 'Training for a strength meet');
  w('## Scenario 8: goal and equipment change\n'); w(`New plan from ${res.effectiveFrom}. Logged sessions: ${s.sessions.length} (unchanged). Saved changes:\n`); res.changes.slice(0, 10).forEach(c => w(`- ${c}`)); w(''); }
// 9 missing check-in, stale Garmin
{ const s = newUser(); const wk = runWeek(s, MON, () => ({ feedback: GOOD }));
  s.wellness = { sleep: [{ date: add(MON, 0), hours: 7.5 }], imports: [{ kind: 'sleep', source: 'garmin', coverage: { from: add(MON, -20), to: add(MON, -10) } }] };
  section('Scenario 9: no check-in and stale wearable data', s, wk, reviewOf(s, wk, null, add(MON, 7)), false, wk.end); }

fs.writeFileSync(path.join(__dirname, '../docs/EXAMPLE-REPORTS.md'), out.join('\n'));
console.log('wrote docs/EXAMPLE-REPORTS.md', out.length, 'lines');
