/* Screenshots of the coaching screens, all from the DEMONSTRATION user generated by simkit.
   node gym/test/screens.cjs /opt/node-tools/node_modules/playwright  <outdir> */
process.env.TZ = 'Australia/Sydney';
const pw = require(process.argv[2]); const fs = require('fs'), http = require('http'), path = require('path');
const OUT = process.argv[3]; const APP = path.join(__dirname, '../public');
const K = require('./simkit.js');
const MIME = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.json': 'application/json', '.webmanifest': 'application/manifest+json', '.png': 'image/png' };
const srv = http.createServer((req, rs) => { const f = path.join(APP, decodeURIComponent(req.url.split('?')[0]).replace(/^\//, '') || 'index.html');
  fs.readFile(f, (e, b) => { if (e) { rs.writeHead(404); rs.end(); return; } rs.writeHead(200, { 'Content-Type': MIME[path.extname(f)] || 'text/plain' }); rs.end(b); }); });
const st = K.newUser({}, '2026-09-07'); K.runWeek(st, '2026-09-07', () => ({ feedback: K.GOOD }));
K.R.addNote(st, { text: 'Bench felt strong, but I was tired by Thursday.', category: 'energy' }, K.msOf('2026-09-10'), 'Australia/Sydney');
delete st._exIndex;
(async () => {
  await new Promise(r => srv.listen(0, '127.0.0.1', r)); const origin = 'http://127.0.0.1:' + srv.address().port + '/';
  const b = await pw.chromium.launch({ executablePath: '/opt/pw-browsers/chromium' }).catch(() => pw.chromium.launch());
  async function page(opts) {
    const ctx = await b.newContext({ viewport: opts.vp, deviceScaleFactor: 2, serviceWorkers: 'block', colorScheme: opts.scheme || 'dark', timezoneId: 'Australia/Sydney' });
    await ctx.addInitScript(s => { localStorage.setItem('recomp.v3', s); }, JSON.stringify(st));
    const p = await ctx.newPage(); await p.clock.install({ time: new Date('2026-09-14T10:30:00+10:00') });
    const errs = []; p.on('pageerror', e => errs.push(e.message));
    await p.goto(origin, { waitUntil: 'load' }); await p.waitForTimeout(1200); await p.clock.resume().catch(() => {});
    return { p, ctx, errs };
  }
  const shot = async (p, name, full) => { await p.waitForTimeout(250); await p.screenshot({ path: path.join(OUT, name + '.png'), fullPage: !!full }); console.log('shot', name); };
  const M = { width: 390, height: 844 };
  let { p, ctx, errs } = await page({ vp: M });
  await shot(p, 'today-mobile-dark', true);
  for (const t of ['plan', 'workouts', 'stretch', 'recovery', 'more']) { await p.evaluate(x => window.__recomp.go(x), t); await shot(p, t + '-mobile-dark', true); }
  await p.evaluate(() => { window.__recomp.go('today'); });
  await p.evaluate(() => { window.ReviewUI ? 0 : 0; });
  await p.evaluate(() => eval('ReviewUI').open()); await shot(p, 'review-1-numbers-mobile');
  await p.click('#vSheet >> text=Continue'); await shot(p, 'review-2-conversation-mobile');
  await p.click('#vSheet >> text=Build my report'); await p.waitForTimeout(600); await shot(p, 'review-3-report-mobile');
  await p.evaluate(() => { const b = document.querySelector('#vSheet .panel'); b.scrollTop = 900; }); await shot(p, 'review-3-report-lower-mobile');
  console.log('errors', errs.join('|') || 'none'); await ctx.close();
  ({ p, ctx, errs } = await page({ vp: M, scheme: 'light' }));
  await shot(p, 'today-mobile-light', true); await p.evaluate(() => window.__recomp.go('plan')); await shot(p, 'plan-mobile-light', true); await ctx.close();
  ({ p, ctx, errs } = await page({ vp: { width: 1280, height: 860 } }));
  await p.evaluate(() => window.__recomp.go('plan')); await shot(p, 'plan-desktop-dark'); await p.evaluate(() => window.__recomp.go('today')); await shot(p, 'today-desktop-dark');
  console.log('errors', errs.join('|') || 'none'); await ctx.close();
  await b.close(); srv.close();
})();
